# This workflow will build a MuleSoft project and deploy to CloudHub

name: Maven build Fetching "settings.xml"

on:
  push:
    branches:
    - feature1
    
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout feature branch
      uses: actions/checkout@v3
      with:
        ref: feature

    - name: Checkout development branch
      uses: actions/checkout@v3
      with:
        ref: development
    #- name: Get branches all
      #run: |
        #git branch -a        
    - name: Get file diff
      run: |
        #git diff remotes/origin/development..remotes/origin/feature -- **/pom.xml >> file_changes.txt
        #cat file_changes.txt
        cd ${GITHUB_WORKSPACE}
        git diff --name-status remotes/origin/development..remotes/origin/feature1 -- "**/pom.xml"
        #cat file_changes.txt        
        
    
